
[tool.black]
line-length = 88
target-version = ['py36']
skip-string-normalization = true
exclude = '''
/(
    \.direnv
  | \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | psycopg2
)/
'''
